#security:
#  oauth2:
#    client:
#      clientId: 659182415690-v6ndf7dlk1eusadl5amagj83fa6t71js.apps.googleusercontent.com
#      clientSecret: -rAJ9mQOUqO-s1QcufB4FJDs
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#      scope:
#        - email
#        - profile
#    resource:
#      userInfoUri: https://graph.facebook.com/me
#
